"""initial

Revision ID: d28c3c8bfa9f
Revises: 
Create Date: 2025-09-01 16:03:32.866525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd28c3c8bfa9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_name', sa.String(length=200), nullable=True),
    sa.Column('feed_code', sa.String(length=100), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'user', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('user', 'admin'),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('user', 'admin'),
               type_=mysql.ENUM('admin', 'user', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))

    op.drop_table('feeds')
    # ### end Alembic commands ###
